name: CI
on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize]
permissions: {}
jobs:
  lint-actions:
    name: GitHub Actions audit
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Run actionlint
        uses: rhysd/actionlint@914e7df21a07ef503a81201c76d2b11c789d3fca # v1.7.12

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@192e21d79ab29983730a13d1382995c2307fbcaa # v0.5.7
        with:
          advanced-security: false

  tests:
    name: Ruby ${{ matrix.ruby }}, ${{ matrix.rails }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.3", "3.4", "4.0", "head"]
        rails: [rails_7_2, rails_8_0, rails_8_1, rails_edge]
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.rails == 'rails_edge' || matrix.ruby == 'head' }}
    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.rails }}.gemfile

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Set up Ruby
        uses: ruby/setup-ruby@9eb537ca036ebaed86729dcb9309076e4c5c3b74 # v1.314.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run tests
        run: bundle exec rake test
