name: CI
on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize]
permissions: {}
jobs:
  lint-actions:
    name: GitHub Actions audit
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Run actionlint
        uses: rhysd/actionlint@914e7df21a07ef503a81201c76d2b11c789d3fca # v1.7.12

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@71321a20a9ded102f6e9ce5718a2fcec2c4f70d8 # v0.5.2
        with:
          advanced-security: false

  tests:
    name: Ruby ${{ matrix.ruby }}, ${{ matrix.rails }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.3", "3.4", "4.0", "head"]
        rails: [rails_7_2, rails_8_0, rails_8_1, rails_edge]
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.rails == 'rails_edge' || matrix.ruby == 'head' }}
    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.rails }}.gemfile

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Set up Ruby
        uses: ruby/setup-ruby@3ff19f5e2baf30647122352b96108b1fbe250c64 # v1.299.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run tests
        run: bundle exec rake test
