name: CI
on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize]
permissions: {}
jobs:
  lint-actions:
    name: GitHub Actions audit
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Run actionlint
        uses: rhysd/actionlint@914e7df21a07ef503a81201c76d2b11c789d3fca # v1.7.12

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@5f14fd08f7cf1cb1609c1e344975f152c7ee938d # v0.5.6
        with:
          advanced-security: false

  tests:
    name: Ruby ${{ matrix.ruby }}, ${{ matrix.rails }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.3", "3.4", "4.0", "head"]
        rails: [rails_7_2, rails_8_0, rails_8_1, rails_edge]
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.rails == 'rails_edge' || matrix.ruby == 'head' }}
    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.rails }}.gemfile

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - name: Set up Ruby
        uses: ruby/setup-ruby@afeafc3d1ab54a631816aba4c914a0081c12ff2f # v1.310.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run tests
        run: bundle exec rake test
