name: CI
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby 2.7
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install libsqlite3-dev

      - name: Install gem dependencies
        run:  gem install bundler && bundle install --jobs 4 --retry 3 --path vendor/bundle

      - name: Run tests
        run: bundle exec rake test
